In [1]:
import torch

In [2]:
torch.__version__

'2.1.0+cu121'

Introduction to Tensors

In [3]:
# scaler
s = torch.tensor(17)
print(s)
s.dtype

tensor(17)


torch.int64

In [4]:
s.shape, s.ndim

(torch.Size([]), 0)

In [5]:
# get the value back as python int; using item() method
s.item(), type(s.item())

(17, int)

In [6]:
# Creating vectors
v =  torch.tensor([4, 17])
print(v)
v.dtype

tensor([ 4, 17])


torch.int64

In [7]:
v.ndim, v.shape

(1, torch.Size([2]))

In [8]:
# creating Matrices
matrix = torch.tensor([[1,2], [3,4]])
matrix

tensor([[1, 2],
        [3, 4]])

In [9]:
matrix.ndim

2

In [10]:
matrix.shape

torch.Size([2, 2])

In [11]:
t = torch.tensor([
    [[51, 2],
    [3, 4]],
    [[14, 12],
    [87, 46]]
])
t

tensor([[[51,  2],
         [ 3,  4]],

        [[14, 12],
         [87, 46]]])

In [12]:
t.shape, t.ndim

(torch.Size([2, 2, 2]), 3)

Creating random tensors

In [13]:
rt = torch.rand(4,3)
rt

tensor([[0.6884, 0.8590, 0.7551],
        [0.0651, 0.2770, 0.1944],
        [0.7175, 0.2729, 0.7958],
        [0.8764, 0.6575, 0.9012]])

In [14]:
rt*10

tensor([[6.8836, 8.5895, 7.5506],
        [0.6507, 2.7703, 1.9437],
        [7.1753, 2.7293, 7.9584],
        [8.7640, 6.5749, 9.0117]])

In [15]:
rt3 = torch.rand(4,2,2)
rt3

tensor([[[0.8539, 0.3917],
         [0.2773, 0.7774]],

        [[0.3790, 0.6135],
         [0.3279, 0.5509]],

        [[0.8223, 0.9527],
         [0.4975, 0.9199]],

        [[0.0536, 0.1105],
         [0.4695, 0.8589]]])

Tensor Operations

In [16]:
# There will be element wise operations
a = torch.tensor([1,3,5])
b = torch.tensor([2,4,6])
a+b

tensor([ 3,  7, 11])

In [17]:
a-b

tensor([-1, -1, -1])

In [18]:
a*b

tensor([ 2, 12, 30])

In [19]:
# scaler addition and multipication
a * 2

tensor([ 2,  6, 10])

In [20]:
b +10

tensor([12, 14, 16])

Matrix Multipication

In [21]:
# getting a dot product of a and b
a.dot(b)

tensor(44)

In [22]:
x = torch.tensor([
    [1,2],
    [3,4]
])

y = torch.tensor([
    [3,1],
    [2,6]
])

In [23]:
# using * will do element wise multipication
x*y

tensor([[ 3,  2],
        [ 6, 24]])

In [24]:
# we can use matmul from torch
torch.matmul(x,y)

tensor([[ 7, 13],
        [17, 27]])