<a href="https://colab.research.google.com/github/mr-rojit/pytorch-basics/blob/main/01_pytorch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
torch.__version__

'2.1.0+cu121'

Introduction to Tensors

In [3]:
# scaler
s = torch.tensor(17)
print(s)
s.dtype

tensor(17)


torch.int64

In [4]:
s.shape, s.ndim

(torch.Size([]), 0)

In [5]:
# get the value back as python int; using item() method
s.item(), type(s.item())

(17, int)

In [6]:
# Creating vectors
v =  torch.tensor([4, 17])
print(v)
v.dtype

tensor([ 4, 17])


torch.int64

In [7]:
v.ndim, v.shape

(1, torch.Size([2]))

In [8]:
# creating Matrices
matrix = torch.tensor([[1,2], [3,4]])
matrix

tensor([[1, 2],
        [3, 4]])

In [9]:
matrix.ndim

2

In [10]:
matrix.shape

torch.Size([2, 2])

In [11]:
t = torch.tensor([
    [[51, 2],
    [3, 4]],
    [[14, 12],
    [87, 46]]
])
t

tensor([[[51,  2],
         [ 3,  4]],

        [[14, 12],
         [87, 46]]])

In [12]:
t.shape, t.ndim

(torch.Size([2, 2, 2]), 3)

Creating random tensors

In [13]:
rt = torch.rand(4,3)
rt

tensor([[0.5061, 0.0566, 0.2459],
        [0.8493, 0.7619, 0.8252],
        [0.7096, 0.6377, 0.7946],
        [0.0638, 0.3344, 0.5757]])

In [14]:
rt*10

tensor([[5.0613, 0.5656, 2.4595],
        [8.4928, 7.6190, 8.2517],
        [7.0963, 6.3768, 7.9457],
        [0.6376, 3.3439, 5.7571]])

In [15]:
rt3 = torch.rand(4,2,2)
rt3

tensor([[[0.4507, 0.9781],
         [0.6203, 0.1221]],

        [[0.7131, 0.4275],
         [0.7550, 0.3000]],

        [[0.1484, 0.2583],
         [0.4624, 0.3079]],

        [[0.3285, 0.2382],
         [0.8283, 0.7059]]])

Tensor Operations

In [16]:
# There will be element wise operations
a = torch.tensor([1,3,5])
b = torch.tensor([2,4,6])
a+b

tensor([ 3,  7, 11])

In [17]:
a-b

tensor([-1, -1, -1])

In [18]:
a*b

tensor([ 2, 12, 30])

In [19]:
# scaler addition and multipication
a * 2

tensor([ 2,  6, 10])

In [20]:
b +10

tensor([12, 14, 16])

Matrix Multipication

In [21]:
# getting a dot product of a and b
a.dot(b)

tensor(44)

In [22]:
x = torch.tensor([
    [1,2],
    [3,4]
])

y = torch.tensor([
    [3,1],
    [2,6]
])

In [23]:
# using * will do element wise multipication
x*y

tensor([[ 3,  2],
        [ 6, 24]])

In [24]:
# we can use matmul from torch
torch.matmul(x,y)

tensor([[ 7, 13],
        [17, 27]])

Tensor Aggregation <br>
using mean max min sum ...

In [25]:
t1 = torch.arange(11,45, 2, dtype=float) # should not be int else we will get error
t1.mean()

tensor(27., dtype=torch.float64)

In [26]:
t1.sum(), t1.max()

(tensor(459., dtype=torch.float64), tensor(43., dtype=torch.float64))

In [27]:
# finding the min and max index using argmin and argmax
t2 = torch.tensor([16,4,67, 345,8,96,3,14])
print(t2.argmin()) # prints 6 as 3 is the min and at 5th index
t2.argmax()

tensor(6)


tensor(3)

In [28]:
t = torch.arange(36)
t

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35])

In [29]:
# reshaping tensor
reshaped = t.reshape(6,6) # should be of compatible shape like 6x6, 36x1, 2x18
reshaped

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])

In [30]:
# stacking tensors
t2 = torch.tensor([3,3,3,3,3,3])
t3  = torch.tensor([3,3,3,3,3,3])+2
torch.stack((t2, t3), dim=1) # by default it will stack horizontally

tensor([[3, 5],
        [3, 5],
        [3, 5],
        [3, 5],
        [3, 5],
        [3, 5]])

In [31]:
# vertically stacking in out 6x6 tensor (reshaped)
torch.vstack((reshaped, t2))

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35],
        [ 3,  3,  3,  3,  3,  3]])

In [32]:
torch.hstack((reshaped, t2.reshape(-1,1))) # converting to compatible format using rehape(-1,1)

tensor([[ 0,  1,  2,  3,  4,  5,  3],
        [ 6,  7,  8,  9, 10, 11,  3],
        [12, 13, 14, 15, 16, 17,  3],
        [18, 19, 20, 21, 22, 23,  3],
        [24, 25, 26, 27, 28, 29,  3],
        [30, 31, 32, 33, 34, 35,  3]])