<a href="https://colab.research.google.com/github/mr-rojit/pytorch-basics/blob/main/01_pytorch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
torch.__version__

'2.1.0+cu121'

Introduction to Tensors

In [3]:
# scaler
s = torch.tensor(17)
print(s)
s.dtype

tensor(17)


torch.int64

In [4]:
s.shape, s.ndim

(torch.Size([]), 0)

In [5]:
# get the value back as python int; using item() method
s.item(), type(s.item())

(17, int)

In [6]:
# Creating vectors
v =  torch.tensor([4, 17])
print(v)
v.dtype

tensor([ 4, 17])


torch.int64

In [7]:
v.ndim, v.shape

(1, torch.Size([2]))

In [8]:
# creating Matrices
matrix = torch.tensor([[1,2], [3,4]])
matrix

tensor([[1, 2],
        [3, 4]])

In [9]:
matrix.ndim

2

In [10]:
matrix.shape

torch.Size([2, 2])

In [11]:
t = torch.tensor([
    [[51, 2],
    [3, 4]],
    [[14, 12],
    [87, 46]]
])
t

tensor([[[51,  2],
         [ 3,  4]],

        [[14, 12],
         [87, 46]]])

In [12]:
t.shape, t.ndim

(torch.Size([2, 2, 2]), 3)

Creating random tensors

In [13]:
rt = torch.rand(4,3)
rt

tensor([[0.7333, 0.1917, 0.9772],
        [0.5831, 0.1893, 0.9784],
        [0.2119, 0.8259, 0.6837],
        [0.9377, 0.2755, 0.4215]])

In [14]:
rt*10

tensor([[7.3332, 1.9168, 9.7716],
        [5.8315, 1.8930, 9.7835],
        [2.1185, 8.2589, 6.8372],
        [9.3774, 2.7545, 4.2151]])

In [15]:
rt3 = torch.rand(4,2,2)
rt3

tensor([[[0.5959, 0.7898],
         [0.2603, 0.2279]],

        [[0.7163, 0.4972],
         [0.3800, 0.6641]],

        [[0.4561, 0.5958],
         [0.0595, 0.7460]],

        [[0.7441, 0.4627],
         [0.7767, 0.3536]]])

Tensor Operations

In [16]:
# There will be element wise operations
a = torch.tensor([1,3,5])
b = torch.tensor([2,4,6])
a+b

tensor([ 3,  7, 11])

In [17]:
a-b

tensor([-1, -1, -1])

In [18]:
a*b

tensor([ 2, 12, 30])

In [19]:
# scaler addition and multipication
a * 2

tensor([ 2,  6, 10])

In [20]:
b +10

tensor([12, 14, 16])

Matrix Multipication

In [21]:
# getting a dot product of a and b
a.dot(b)

tensor(44)

In [22]:
x = torch.tensor([
    [1,2],
    [3,4]
])

y = torch.tensor([
    [3,1],
    [2,6]
])

In [23]:
# using * will do element wise multipication
x*y

tensor([[ 3,  2],
        [ 6, 24]])

In [24]:
# we can use matmul from torch
torch.matmul(x,y)

tensor([[ 7, 13],
        [17, 27]])