In [1]:
import torch

In [2]:
torch.__version__

'2.1.0+cu121'

Introduction to Tensors

In [7]:
# scaler
s = torch.tensor(17)
print(s)
s.dtype

tensor(17)


torch.int64

In [9]:
s.shape, s.ndim

(torch.Size([]), 0)

In [12]:
# get the value back as python int; using item() method
s.item(), type(s.item())

(17, int)

In [13]:
# Creating vectors
v =  torch.tensor([4, 17])
print(v)
v.dtype

tensor([ 4, 17])


torch.int64

In [15]:
v.ndim, v.shape

(1, torch.Size([2]))

In [16]:
# creating Matrices
matrix = torch.tensor([[1,2], [3,4]])
matrix

tensor([[1, 2],
        [3, 4]])

In [17]:
matrix.ndim

2

In [18]:
matrix.shape

torch.Size([2, 2])

In [24]:
t = torch.tensor([
    [[51, 2],
    [3, 4]],
    [[14, 12],
    [87, 46]]
])
t

tensor([[[51,  2],
         [ 3,  4]],

        [[14, 12],
         [87, 46]]])

In [25]:
t.shape, t.ndim

(torch.Size([2, 2, 2]), 3)

Creating random tensors

In [26]:
rt = torch.rand(4,3)
rt

tensor([[0.8772, 0.0139, 0.9021],
        [0.0876, 0.4662, 0.6426],
        [0.5464, 0.7227, 0.8716],
        [0.8582, 0.7881, 0.5640]])

In [27]:
rt*10

tensor([[8.7722, 0.1389, 9.0211],
        [0.8757, 4.6616, 6.4264],
        [5.4640, 7.2273, 8.7157],
        [8.5824, 7.8810, 5.6404]])

In [30]:
rt3 = torch.rand(4,2,2)
rt3

tensor([[[0.2879, 0.5634],
         [0.7402, 0.9323]],

        [[0.0672, 0.8519],
         [0.1987, 0.8175]],

        [[0.1261, 0.9043],
         [0.6411, 0.1704]],

        [[0.7435, 0.3677],
         [0.3109, 0.5883]]])