<a href="https://colab.research.google.com/github/mr-rojit/pytorch-basics/blob/main/pytorch_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Tensor Basics



In [1]:
import torch

A
tensor is an array: that is, a data structure that stores a collection of numbers that are accessible individually using an index, and that can be indexed with multiple indices.

In [2]:
a = torch.tensor(1)
a

tensor(1)

In [3]:
a.dtype

torch.int64

In [4]:
# creating tensor with 3 ones and zeros
torch.ones(3), torch.zeros(3)


(tensor([1., 1., 1.]), tensor([0., 0., 0.]))

In [5]:
# creating multimentional ones
x = torch.ones(5,5)
x

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [6]:
# creating tensor with arange and reshaping
x = torch.arange(25).reshape(5,5)
x

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])

In [7]:
x.size()

torch.Size([5, 5])

In [8]:
x.shape

torch.Size([5, 5])

In [9]:
# slicing the tensor object
print(x[:, 1])  # all rows for column 1

tensor([ 1,  6, 11, 16, 21])


In [10]:
x[-2:, -2:] # selecting last square

tensor([[18, 19],
        [23, 24]])

In [11]:
 # generating random number tensor using randn
 torch.randn(2, 3, 5, 5)

tensor([[[[ 0.7598, -0.4753,  1.6041, -1.3979, -1.1074],
          [ 0.6912, -0.9188, -0.3567, -0.1687,  1.1361],
          [ 0.6883, -0.4736, -0.5451, -1.4738,  0.2502],
          [ 1.8856,  0.2118,  2.3548, -1.6191,  0.9984],
          [ 1.8619, -0.1824,  1.5278,  1.1053,  1.0730]],

         [[-1.0773, -0.0840, -0.3996,  1.5316,  0.3858],
          [-2.2782, -0.9343,  0.1513,  0.8335, -0.0629],
          [ 0.3210, -0.5942,  1.1984, -2.3289,  0.0761],
          [-1.5453,  0.3245, -0.3282, -0.1861, -1.0189],
          [-1.7208,  0.5930, -0.8373,  2.3983,  0.5823]],

         [[-0.8877, -0.0361,  0.3393, -0.8331, -0.9037],
          [ 0.5425,  0.0353,  1.1095, -0.2035,  0.8086],
          [ 0.4405, -0.1530,  2.6373,  1.0950, -0.7117],
          [ 0.6210, -1.5394, -0.2891, -0.0041,  0.2694],
          [-0.2941,  0.6258, -0.1718,  0.0763, -1.3033]]],


        [[[ 0.5849, -1.5148,  0.6133, -0.1232,  0.7572],
          [-2.0075, -1.8055, -0.0394,  0.2301,  1.1999],
          [ 0.9281,  0.

Transposing the tensor

In [12]:
x

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])

In [13]:
x.t()

tensor([[ 0,  5, 10, 15, 20],
        [ 1,  6, 11, 16, 21],
        [ 2,  7, 12, 17, 22],
        [ 3,  8, 13, 18, 23],
        [ 4,  9, 14, 19, 24]])

In [14]:
torch.mean(x.to(torch.float), dim=1)

tensor([ 2.,  7., 12., 17., 22.])

In [15]:
x[x%2==0]

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

## Attributes of a Tensor

** Tensor attributes describe their shape, datatype, and the device on which they are stored. **



In [16]:
print(f"Shape of tensor: {x.shape}")
print(f"Datatype of tensor: {x.dtype}")
print(f"Device tensor is stored on: {x.device}")

Shape of tensor: torch.Size([5, 5])
Datatype of tensor: torch.int64
Device tensor is stored on: cpu


### Simple tensor operations

In [17]:
a = torch.ones(1,5)
b = torch.zeros(1,5)
a, b

(tensor([[1., 1., 1., 1., 1.]]), tensor([[0., 0., 0., 0., 0.]]))

In [18]:
torch.cat([a,b], dim=1)

tensor([[1., 1., 1., 1., 1., 0., 0., 0., 0., 0.]])

Matrix multipication

In [21]:
a = torch.tensor([[1,2], [3,4]])
b = torch.tensor([
    [5,6,2],
    [7,8,2]
])

In [23]:
a@b

tensor([[19, 22,  6],
        [43, 50, 14]])

In [24]:
torch.matmul(a,b)

tensor([[19, 22,  6],
        [43, 50, 14]])